server:
  port: 9002

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: eureka02
    instance-id: eureka-server2
    prefer-ip-address: off
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01:9001/eureka/
  server:
    enable-self-preservation: false
