server:
  port: 9000

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: wno704    # eureka 实例名称
    instance-id: eureka-server
    prefer-ip-address: off
  client:
    register-with-eureka: true     # 是否向注册中心注册自己
    fetch-registry: false           # 是否检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 注册中心访问地址

